"""Optional tenant-owned runtime contracts and secure execution kernel.

Install ``prometa-sdk[runtime]`` for cryptographic admission, JSON Schema
enforcement, and the Phase 2A kernel. The default ``prometa-sdk`` installation
remains dependency-free and telemetry-first, and no execution path calls the
Orchestra control plane synchronously. Install
``prometa-sdk[runtime-postgres]`` only for the optional shared durability
adapters, or ``prometa-sdk[runtime-host]`` for the first tenant-deployed
model-only host and its PostgreSQL dependency.
"""

from .trust import (
    BundleTrustEntry,
    BundleTrustStore,
    BundleVerificationError,
    VerifiedBundle,
    VerifiedPromotionAttestation,
    verify_bundle_envelope,
    verify_promotion_attestation,
)
from .receipts import (
    RuntimeReceiptClient,
    RuntimeReceiptError,
    RuntimeReceiptSubmissionError,
    build_runtime_receipt,
)
from .admission import (
    RUNTIME_CONTRACT_VERSION,
    CAPABILITY_MODEL_INVOKE,
    CAPABILITY_EVIDENCE_EMIT,
    CAPABILITY_SCHEMA_VALIDATE,
    CAPABILITY_GUARD_EVALUATE,
    CAPABILITY_TOOL_BROKER,
    CAPABILITY_HUMAN_ESCALATION,
    BASE_RUNTIME_CAPABILITIES,
    KNOWN_RUNTIME_CAPABILITIES,
    RuntimeManifest,
    RuntimeModel,
    RuntimeTool,
    RuntimeGuardrail,
    RuntimeContract,
    RuntimeBundleConfig,
    RuntimeAdmissionPolicy,
    AdmittedRuntimeRelease,
    RuntimeActivationResult,
    AdmissionReplayStore,
    RuntimeActivationStore,
    InMemoryAdmissionReplayStore,
    InMemoryRuntimeActivationStore,
    parse_runtime_bundle,
    admit_runtime_release,
    activate_runtime_release,
)
from .kernel import (
    RuntimeExecutionError,
    ModelAdapterError,
    RuntimeEvidenceEvent,
    EvidenceEmitter,
    InMemoryEvidenceEmitter,
    PrometaEvidenceEmitter,
    ModelToolCall,
    ModelInvocationRequest,
    ModelInvocationResponse,
    ModelAdapter,
    GuardRequest,
    GuardDecision,
    GuardEvaluator,
    HumanEscalationRequest,
    HumanEscalationDecision,
    HumanEscalation,
    ToolInvocationRequest,
    ToolInvocationResult,
    ToolBroker,
    DenyAllToolBroker,
    RuntimeStateStore,
    InMemoryRuntimeStateStore,
    RuntimeExecutionPolicy,
    RuntimeExecutionResult,
    available_runtime_capabilities,
    RuntimeKernel,
)
from .model_gateway import OpenAICompatibleModelAdapter
from .postgres import (
    RuntimePersistenceError,
    RuntimeStateRecord,
    install_postgres_runtime_schema,
    PostgresAdmissionReplayStore,
    PostgresRuntimeActivationStore,
    PostgresRuntimeStateStore,
)
from .conformance import (
    CONFORMANCE_REPORT_VERSION,
    CONFORMANCE_COMMAND_PROTOCOL_VERSION,
    CONFORMANCE_PROFILES,
    RuntimeConformanceCase,
    RuntimeConformanceObservation,
    RuntimeConformanceDriver,
    RuntimeConformanceProtocolError,
    RuntimeConformanceCheck,
    RuntimeConformanceReport,
    SdkRuntimeConformanceDriver,
    SubprocessRuntimeConformanceDriver,
    load_runtime_conformance_fixture,
    run_runtime_conformance,
    runtime_conformance_command_main,
)
from .host import (
    HOST_CONFIG_VERSION,
    DEFAULT_MAX_REQUEST_BYTES,
    DEFAULT_REQUEST_TIMEOUT_SECONDS,
    RuntimeHostError,
    RuntimeHostConfig,
    RuntimeHostResponse,
    JsonLineEvidenceEmitter,
    ReferenceRuntimeHost,
    load_runtime_host_config,
    build_reference_runtime_host,
    serve_reference_runtime_host,
)
from .host_conformance import ReferenceHostConformanceDriver

__all__ = [
    "BundleTrustEntry",
    "BundleTrustStore",
    "BundleVerificationError",
    "VerifiedBundle",
    "VerifiedPromotionAttestation",
    "verify_bundle_envelope",
    "verify_promotion_attestation",
    "RuntimeReceiptClient",
    "RuntimeReceiptError",
    "RuntimeReceiptSubmissionError",
    "build_runtime_receipt",
    "RUNTIME_CONTRACT_VERSION",
    "CAPABILITY_MODEL_INVOKE",
    "CAPABILITY_EVIDENCE_EMIT",
    "CAPABILITY_SCHEMA_VALIDATE",
    "CAPABILITY_GUARD_EVALUATE",
    "CAPABILITY_TOOL_BROKER",
    "CAPABILITY_HUMAN_ESCALATION",
    "BASE_RUNTIME_CAPABILITIES",
    "KNOWN_RUNTIME_CAPABILITIES",
    "RuntimeManifest",
    "RuntimeModel",
    "RuntimeTool",
    "RuntimeGuardrail",
    "RuntimeContract",
    "RuntimeBundleConfig",
    "RuntimeAdmissionPolicy",
    "AdmittedRuntimeRelease",
    "RuntimeActivationResult",
    "AdmissionReplayStore",
    "RuntimeActivationStore",
    "InMemoryAdmissionReplayStore",
    "InMemoryRuntimeActivationStore",
    "parse_runtime_bundle",
    "admit_runtime_release",
    "activate_runtime_release",
    "RuntimeExecutionError",
    "ModelAdapterError",
    "RuntimeEvidenceEvent",
    "EvidenceEmitter",
    "InMemoryEvidenceEmitter",
    "PrometaEvidenceEmitter",
    "ModelToolCall",
    "ModelInvocationRequest",
    "ModelInvocationResponse",
    "ModelAdapter",
    "GuardRequest",
    "GuardDecision",
    "GuardEvaluator",
    "HumanEscalationRequest",
    "HumanEscalationDecision",
    "HumanEscalation",
    "ToolInvocationRequest",
    "ToolInvocationResult",
    "ToolBroker",
    "DenyAllToolBroker",
    "RuntimeStateStore",
    "InMemoryRuntimeStateStore",
    "RuntimeExecutionPolicy",
    "RuntimeExecutionResult",
    "available_runtime_capabilities",
    "RuntimeKernel",
    "OpenAICompatibleModelAdapter",
    "RuntimePersistenceError",
    "RuntimeStateRecord",
    "install_postgres_runtime_schema",
    "PostgresAdmissionReplayStore",
    "PostgresRuntimeActivationStore",
    "PostgresRuntimeStateStore",
    "CONFORMANCE_REPORT_VERSION",
    "CONFORMANCE_COMMAND_PROTOCOL_VERSION",
    "CONFORMANCE_PROFILES",
    "RuntimeConformanceCase",
    "RuntimeConformanceObservation",
    "RuntimeConformanceDriver",
    "RuntimeConformanceProtocolError",
    "RuntimeConformanceCheck",
    "RuntimeConformanceReport",
    "SdkRuntimeConformanceDriver",
    "SubprocessRuntimeConformanceDriver",
    "load_runtime_conformance_fixture",
    "run_runtime_conformance",
    "runtime_conformance_command_main",
    "HOST_CONFIG_VERSION",
    "DEFAULT_MAX_REQUEST_BYTES",
    "DEFAULT_REQUEST_TIMEOUT_SECONDS",
    "RuntimeHostError",
    "RuntimeHostConfig",
    "RuntimeHostResponse",
    "JsonLineEvidenceEmitter",
    "ReferenceRuntimeHost",
    "load_runtime_host_config",
    "build_reference_runtime_host",
    "serve_reference_runtime_host",
    "ReferenceHostConformanceDriver",
]
