"""Optional shared guardrail evaluation for the tenant-owned runtime.

This subpackage carries the ``orchestra-guardrail-evaluate-v1`` codec and the
first shipped ``GuardEvaluator``, so a signed bundle that declares guardrails is
admissible without every tenant writing a detector first. Install
``prometa-sdk[guardrail]`` alongside the runtime extra; the default
``prometa-sdk`` installation stays dependency-free and telemetry-first, and
nothing here calls the Orchestra control plane in the request path.
"""

from .contract import (
    GUARDRAIL_CONTRACT,
    GUARDRAIL_CONTRACT_MAX_SUPPORTED,
    GUARDRAIL_CONTRACT_MIN_SUPPORTED,
    GUARDRAIL_CONTRACT_VERSION,
    GUARDRAIL_EVALUATE_PATH,
    GUARDRAIL_FAIL_MODES,
    GUARDRAIL_STAGES,
    GUARDRAIL_VERDICTS,
    DEFAULT_FAIL_OPEN_MAX_CONSECUTIVE,
    DEFAULT_FAIL_OPEN_WINDOW_SECONDS,
    DEFAULT_MAX_PAYLOAD_BYTES,
    DEFAULT_STAGE_BUDGET_MS,
    DEFAULT_TRANSPORT_SLACK_MS,
    HTTP_STATUS_REASON_CODES,
    KERNEL_STAGE_TO_WIRE,
    GuardrailContractError,
    GuardrailResponse,
    GuardrailSubject,
    GuardrailSpanRecorder,
    applicable_guardrail_names,
    decode_evaluate_response,
    encode_evaluate_request,
    guardrail_span_attributes,
    wire_stage,
)
from .failmode import (
    FailOpenBudget,
    FailOpenObserver,
    GuardrailUnavailableError,
    apply_fail_mode,
    resolve_fail_mode,
)
from .profiles import (
    GuardrailProfile,
    GuardrailProfileError,
    assert_fail_open_permitted,
    guardrail_is_observe_only,
    load_guardrail_definitions,
    load_guardrail_profile,
    load_guardrail_profiles,
)
from .detectors import (
    BUILTIN_DETECTOR_KINDS,
    BUILTIN_PACK_ID,
    BUILTIN_PACK_VERSION,
    Detector,
    DetectorContext,
    DetectorError,
    DetectorFinding,
    DetectorPack,
    DetectorSpan,
    build_builtin_pack,
    build_detector_pack,
    normalize_text,
    register_detector_factory,
    unregister_detector_factory,
)
from .service import (
    GuardrailRequestError,
    GuardrailService,
    GuardrailServiceResponse,
    LocalGuardEvaluator,
)
from .streaming import (
    StreamWindow,
    StreamingGuardWindow,
    stream_windows,
    streaming_guard_window,
)
from .client import (
    GuardrailTransport,
    GuardrailTransportResult,
    HttpGuardEvaluator,
    UrllibGuardrailTransport,
)
from .host import (
    GUARDRAIL_HOST_CONFIG_VERSION,
    GuardrailApiKey,
    GuardrailHostConfig,
    GuardrailHostError,
    GuardrailServiceHost,
    JsonLineGuardrailLogger,
    build_guardrail_service_host,
    load_guardrail_api_keys,
    load_guardrail_host_config,
    serve_guardrail_service,
)
from .conformance import (
    CHECK_IDS,
    DELEGATED_CHECKS,
    GuardrailConformanceCheck,
    GuardrailConformanceDriver,
    GuardrailConformanceReport,
    LocalGuardrailConformanceDriver,
    build_conformance_driver,
    build_conformance_service,
    run_guardrail_conformance,
)


__all__ = [
    "BUILTIN_DETECTOR_KINDS",
    "BUILTIN_PACK_ID",
    "BUILTIN_PACK_VERSION",
    "CHECK_IDS",
    "DELEGATED_CHECKS",
    "GUARDRAIL_HOST_CONFIG_VERSION",
    "GUARDRAIL_CONTRACT",
    "GUARDRAIL_CONTRACT_MAX_SUPPORTED",
    "GUARDRAIL_CONTRACT_MIN_SUPPORTED",
    "GUARDRAIL_CONTRACT_VERSION",
    "GUARDRAIL_EVALUATE_PATH",
    "GUARDRAIL_FAIL_MODES",
    "GUARDRAIL_STAGES",
    "GUARDRAIL_VERDICTS",
    "DEFAULT_FAIL_OPEN_MAX_CONSECUTIVE",
    "DEFAULT_FAIL_OPEN_WINDOW_SECONDS",
    "DEFAULT_MAX_PAYLOAD_BYTES",
    "DEFAULT_STAGE_BUDGET_MS",
    "DEFAULT_TRANSPORT_SLACK_MS",
    "HTTP_STATUS_REASON_CODES",
    "KERNEL_STAGE_TO_WIRE",
    "Detector",
    "DetectorContext",
    "DetectorError",
    "DetectorFinding",
    "DetectorPack",
    "DetectorSpan",
    "FailOpenBudget",
    "FailOpenObserver",
    "GuardrailApiKey",
    "GuardrailConformanceCheck",
    "GuardrailConformanceDriver",
    "GuardrailConformanceReport",
    "GuardrailContractError",
    "GuardrailHostConfig",
    "GuardrailHostError",
    "GuardrailProfile",
    "GuardrailProfileError",
    "GuardrailRequestError",
    "GuardrailResponse",
    "GuardrailService",
    "GuardrailServiceHost",
    "GuardrailServiceResponse",
    "GuardrailSpanRecorder",
    "GuardrailSubject",
    "JsonLineGuardrailLogger",
    "LocalGuardrailConformanceDriver",
    "GuardrailTransport",
    "GuardrailTransportResult",
    "GuardrailUnavailableError",
    "HttpGuardEvaluator",
    "LocalGuardEvaluator",
    "StreamWindow",
    "StreamingGuardWindow",
    "UrllibGuardrailTransport",
    "applicable_guardrail_names",
    "apply_fail_mode",
    "assert_fail_open_permitted",
    "build_builtin_pack",
    "build_conformance_driver",
    "build_conformance_service",
    "build_detector_pack",
    "build_guardrail_service_host",
    "decode_evaluate_response",
    "encode_evaluate_request",
    "guardrail_is_observe_only",
    "load_guardrail_definitions",
    "guardrail_span_attributes",
    "load_guardrail_api_keys",
    "load_guardrail_host_config",
    "load_guardrail_profile",
    "load_guardrail_profiles",
    "normalize_text",
    "register_detector_factory",
    "resolve_fail_mode",
    "run_guardrail_conformance",
    "serve_guardrail_service",
    "stream_windows",
    "streaming_guard_window",
    "unregister_detector_factory",
    "wire_stage",
]
